# Office: Dell S3221QS (workspaces 2, 3, 4)
workspace = 2, monitor:desc:Dell Inc. DELL S3221QS CJCV6N3
workspace = 3, monitor:desc:Dell Inc. DELL S3221QS CJCV6N3
workspace = 4, monitor:desc:Dell Inc. DELL S3221QS CJCV6N3
