# Home: LG Ultrawide (1-5)
workspace = 1, monitor:desc:LG Electronics LG ULTRAWIDE 0x00060DD4, name:💬1, persistent:true
workspace = 2, monitor:desc:LG Electronics LG ULTRAWIDE 0x00060DD4, name:🌐2, persistent:true
workspace = 3, monitor:desc:LG Electronics LG ULTRAWIDE 0x00060DD4, persistent:true
workspace = 4, monitor:desc:LG Electronics LG ULTRAWIDE 0x00060DD4, persistent:true
workspace = 5, monitor:desc:LG Electronics LG ULTRAWIDE 0x00060DD4, persistent:true

# Home: Dell S3220DGF (6-10)
workspace = 6, monitor:desc:Dell Inc. DELL S3220DGF JNYSF43, name:💻6, persistent:true
workspace = 7, monitor:desc:Dell Inc. DELL S3220DGF JNYSF43, name:📧7, persistent:true
workspace = 8, monitor:desc:Dell Inc. DELL S3220DGF JNYSF43, name:🗄️8, persistent:true
workspace = 9, monitor:desc:Dell Inc. DELL S3220DGF JNYSF43, persistent:true
workspace = 10, monitor:desc:Dell Inc. DELL S3220DGF JNYSF43, name:10, persistent:true
