# @dots-version: 1
# Local machine configuration
# This file is imported by hyprland.conf

# === Environment Variables ===

# Sample block for Desktop with NVIDIA GPU
# NVIDIA GPU
# env = NVD_BACKEND,direct
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
