# App to workspace rules (by initialClass)
windowrule = workspace 1, match:class Slack
windowrule = workspace 1, match:class spotify
windowrule = workspace 2, match:class brave-browser
windowrule = workspace 7, match:class brave-app.hey.com__-Default
windowrule = workspace 6, match:class com.mitchellh.ghostty
windowrule = workspace 8, match:class DBeaver
