[env]
_.path = ["{{ cwd }}/node_modules/.bin", "{{ cwd }}/.venv/bin", "{{ cwd }}/bin"]
_.file = {path = "{{ env.HOME }}/.config/mise/secrets.env", redact = true}
MISE_GO_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-go-packages"

[tools]
node = "latest"
go = "latest"
rust = "latest"
python = "latest"
bun = "latest"
deno = "latest"
java = "latest"
zig = "latest"

air = "latest"
atlas = "latest"
lefthook = "latest"
jq = "latest"
shfmt = "latest"

"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"

"npm:yaml-language-server" = "latest"
"pipx:sqlfmt" = "latest"
"pipx:mdformat" = "latest"
